config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'confirmations' }
  resources :about
  resources :contacts
  get 'about' => 'about#index'
  get '/search' => 'posts#search', as: 'search_posts'
  resources :posts do
  	member do 
  		get "like", to: "posts#upvote"
  		get "dislike", to: "posts#downvote"
  	end
    
  	resources :comments
  end

  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	
end

app/models/post.rb
class Post < ApplicationRecord
	acts_as_votable
	belongs_to :user
	has_many :comments
	belongs_to :category

	scoped_search on: [:name]
  	# named_scope :public, conditions: { public: true }


    has_attached_file :image, styles: { medium: "700x500>", small: "450x350>" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

    has_many :posts
    has_many :comments
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
	def index
		
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :authenticate_user!

	def create
		@post = Post.find(params[:post_id])
		@comment = Comment.create(params[:comment].permit(:content))
		@comment.user_id = current_user.id
		@comment.post_id = @post.id


		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  private
  def after_confirmation_path_for(resource_name, resource)
    root_path
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		
	end

	def create
		
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
	before_action :authenticate_user!, except: [:show, :index]

	def search
		if params[:search].present?
			@posts = Post.search_for(params[:search])
		else
			@posts = Post.all.order("created_at ASC")
		end
	end


	def index

		if params[:category].blank?
			@posts = Post.all.order("created_at ASC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@posts = Post.where(category_id: @category_id).order("created_at DESC")
		end
	end

	def show
		@comments = Comment.where(post_id: @post)
		@random_post = Post.where.not(id: @post).order("RANDOM()").first

	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

	def upvote
		@post.upvote_by current_user
		redirect_to :back
	end

	def downvote
		@post.downvote_from current_user
		redirect_to :back
	end

	private

	def find_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:position, :name, :breifHistory, :education, :achievments,  :goals, :image, :category_id)
	end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/about/index.html.haml
%section.team
  .container
    .row
      .col-md-10.col-md-offset-1.col-md-10.col-sm-offset-1.text-center
        %h1 YOUR CHOICE IS WHAT WILL LEAD YOU
        .border.center-block
        %p{:style => "font-size: 2rem; font-weight: 400;"} Have you ever seen a post and would like to say something about that candidate whether good or bad depending on your opinion and view toward that candidate?
        %p{:style => "font-size: 2rem; font-weight: 400;"} Well this platform is for the 2017 election campaign to help the citizen and candidate interact with each other and share what they think about each other, so, sign up and share your opinion with your candidates
        %h2 What you can do on this platform!
        %ul{:style => "text-align: left; font-size: 2rem; font-weight: 400;"}
          %li Sign up for free
          %li Check candidates from your county only
          %li search for a candidate using the candidate's name
          %li comment and share your opinion about the candidate
          %li upvote or downvote the candidate for him or her to know his position before even voting happens
          %li Share the candidate's profile in any socail media eg facebook, twitter etc
        %h1 Want to your profile uploaded
        %h2 Email us on "arteppal@gmail.com" for instructions
          

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build]) do |f|
	=f.input :content, label: "Reply to thread"
	=f.button :submit, class: "btn btn-primary"

app/views/layouts/application.html.haml
!!!
%html
%head
	%title Your | Choice
	= csrf_meta_tags
	= stylesheet_link_tag    'application', media: 'all'
	= javascript_include_tag 'application'
	= analytics_init if GoogleAnalytics.valid_tracker?
	%link{:rel => "stylesheet", :href => "https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css"}
	%link{:rel => "stylesheet", :href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"}


%body
	%nav.navbar.navbar-default
		.container{:style => "width: 90%;"}
			.navbar-brand
				= link_to "Future choice", root_path 
			- if user_signed_in?
				%ul.nav.navbar-nav.navbar-right
					%li= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-default'
					%li= link_to "About us", about_index_path, class: 'btn btn-default'
					- if current_user.admin?
						%li= link_to "New Post", new_post_path, class: 'btn btn-default'
					
				/ %ul.nav.navbar-nav.navbar-right
				/   .dropdown
				/     %button#dropdownMenu1.btn.btn-default.dropdown-toggle{"aria-expanded" => "true", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"} Check your county
				/     / %span.caret
				/     %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu"}
				/       - Category.all.each do |category|
				/         %li= link_to category.name, posts_path(category: category.name)
						
			- else
				%ul.nav.navbar-nav.navbar-right 
					%li= link_to "Sign In", new_user_session_path, class: 'btn btn-default'
					%li= link_to "Sign Up", new_user_registration_path, class: 'btn btn-default'
					%li= link_to "About us", about_index_path, class: 'btn btn-default'
					
				/ %ul.nav.navbar-nav.navbar-right
				/   .dropdown
				/     %button#dropdownMenu1.btn.btn-default.dropdown-toggle{"aria-expanded" => "true", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"} Check your county
				/     / %span.caret
				/     %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu"}
				/       - Category.all.each do |category|
				/         %li= link_to category.name, posts_path(category: category.name)
	%p= notice
	%p= alert
	.wrapper
		= yield
	/ %hr 
	/ .footer
	/ 	.row
	/ 		.col-sm-4.col-sm-offset-4.text-center
	/ 			%h1 Services To Our Clients
	/ 			%hr
	/ 			%h3.text-center Campaign Websites
	/ 			%h3.text-center Social Media Marketing
	/ 			%hr
	/ 			.row
	/ 				.col-sm-4.text-center
	/ 					.btn-group
	/ 						%button.btn.btn-primary
	/ 							%em.fa.fa-fw.fa-facebook-f
	/ 				.col-sm-4.text-center
	/ 					.btn-group
	/ 						%button.btn.btn-info
	/ 							%em.fa.fa-fw.fa-twitter
	/ 				.col-sm-4.text-center
	/ 					.btn-group
	/ 						%button.btn.btn-warning
	/ 							%em.fa.fa-fw.fa-instagram
	/ 			%hr
				

	

app/views/posts/_form.html.haml
.col-md-6.col-md-offset-3
	.row
		.panel.panel-default
			.panel-heading
				%h2 New Post
			.panel-body
			= simple_form_for @post do |f|
				.form-group
					=f.collection_select :category_id, Category.all, :id, :name, {promt: 'County running for'}, input_html: { class: 'form-control' }
				.form-group
					=f.input :image, input_html: { class: 'form-control' }
				.form-group
					=f.input :name, input_html: { class: 'form-control' }
				.form-group
					=f.input :position, input_html: { class: 'form-control' }
				.form-group
					=f.input :breifHistory, input_html: { class: 'form-control' }
				.form-group
					=f.input :education, input_html: { class: 'form-control' }
				.form-group
					=f.input :achievments, input_html: { class: 'form-control' }
				.form-group
					=f.input :goals, input_html: { class: 'form-control' }

				.form-actions
					= f.button :submit, class: 'btn btn-primary'

app/views/posts/edit.html.haml
%h1 Edit your profile

= render 'form'

app/views/posts/index.html.haml
.row
	.box
		.col-lg-12.text-center
			#carousel-example-generic.carousel.slide
				%ol.carousel-indicators.hidden-xs
					%li.active{"data-slide-to" => "0", "data-target" => "#carousel-example-generic"}
					%li{"data-slide-to" => "1", "data-target" => "#carousel-example-generic"}
					%li{"data-slide-to" => "2", "data-target" => "#carousel-example-generic"}
				.carousel-inner
					.item.active
						.img-responsive.img-full
							= image_tag("voter.jpg")
						.container
							.carousel-caption
								%h1{:style => "color: green;"}
									YOUR CHOICE, YOUR FUTURE.
								%h2{:style => "padding-left: 2rem;"}
									You can read, comment, upvote or downvote and share your favorite candidate's profile on socail media.
								= link_to "Sign Up Today", new_user_registration_path, class: 'btn btn-primary'

					.item
						.img-responsive.img-full
							= image_tag("election2.jpg")
						.container
							.carousel-caption
								%h1{:style => "color: green;"}
									YOUR VOTE COUNTS.
								%h2{:style => "padding-left: 2rem;"}
									You can interact with all the candidates of 2017 election, So sign up now.
								= link_to "About us", about_index_path, class: 'btn btn-primary'

					.item
						.img-responsive.img-full
							= image_tag("somv.jpg")
						.container
							.carousel-caption
								%h1{:style => "color: green;"}
									CHOOSE RIGHT TO VOTE SMART.
								%h2{:style => "padding-left: 2rem;"}
									You can sign up for free and for  candidates please share with us your profile.
								= link_to "Sign Up Today", new_user_registration_path, class: 'btn btn-primary'
				/ Controls
				%a.left.carousel-control{"data-slide" => "prev", :href => "#carousel-example-generic"}
					%span.icon-prev
				%a.right.carousel-control{"data-slide" => "next", :href => "#carousel-example-generic"}
					%span.icon-next


- if user_signed_in?
	%p#intro 
		Hello
		= current_user.name
		%br
		%span
			To upload your profile email us "arteppal@gmail.com"!
	#intro
		.row
			.col-md-4.col-md-offset-4{:style => "padding-left: 2rem;"}
				%h3{:style => "margin-top: 0; font-size: 2.3rem;"} Search Candidate's name
				= form_tag search_posts_path, method: :get, class: "navbar-form", role: "search" do
					%p
						= text_field_tag :search, params[:search], class: "form-control"
						= submit_tag "Search", name: nil, class: "btn btn-default"
- else
	%p#intro
		Sign up and share your opinion
		%br
		%span
			To upload your profile email us "arteppal@gmail.com"!
	#intro
		.row
			.col-md-4.col-md-offset-4{:style => "padding-left: 2rem;"}
				%h3{:style => "margin-top: 0; font-size: 2.3rem;"} Search Candidate's name
				= form_tag search_posts_path, method: :get, class: "navbar-form", role: "search" do
					%p
						= text_field_tag :search, params[:search], class: "form-control"
						= submit_tag "Search", name: nil, class: "btn btn-default"
.container
	%ul.nav.navbar-nav
		- Seat.all.each do |seat|
			%li= link_to seat.name, posts_path(seat: seat.name)
#posts.transitions-enabled
	- @posts.each do |post|
		.box.post
			.post_image
				= link_to (image_tag post.image.url(:small)), post
			.post_content
				.title
					%h2= post.name
				.data.clearfix
					%p.username
						= post.position
					%p.buttons
						%span
							%i.fa.fa-comments-o
							= post.comments.count
						%span
							%i.fa.fa-thumbs-o-up
							= post.get_likes.size
						%span
							%i.fa.fa-thumbs-o-down
							= post.get_dislikes.size
%hr
.row
	.col-sm-4.col-sm-offset-4.text-center
		%h1 Our Services
		%hr
		
		%h3.text-center Campaign Websites
		%h3.text-center Campaign video ads
		%h3.text-center Social Media Marketing

		%hr
		.row
			.col-sm-4
				.btn-group
					%button.btn.btn-primary.text-center
						%em.fa.fa-fw.fa-facebook-f
			.col-sm-4
				.btn-group
					%button.btn.btn-info.text-center
						%em.fa.fa-fw.fa-twitter
			.col-sm-4
				.btn-group
					%button.btn.btn-warning.text-center
						%em.fa.fa-fw.fa-instagram
		%hr
			

app/views/posts/new.html.haml
.col-md-6.col-md-offset-3
	%h1 Add your profile here.

= render 'form'

app/views/posts/search.html.haml
- if user_signed_in?
	%p#intro
		Hello
		= current_user.name
		%br
		%span
			Tell us what you think about this candidates!
	#intro
		.row
			.col-md-4.col-md-offset-4{:style => "padding-left: 2rem;"}
				%h3{:style => "margin-top: 0; font-size: 2.3rem;"} Search Candidate's name
				= form_tag search_posts_path, method: :get, class: "navbar-form", role: "search" do
					%p
						= text_field_tag :search, params[:search], class: "form-control"
						= submit_tag "Search", name: nil, class: "btn btn-default"
- else
	%p#intro
		Sign up and share your opinion
		%br
		%span
			Tell us what you think about this candidates!
	#intro
		.row
			.col-md-4.col-md-offset-4{:style => "padding-left: 2rem;"}
				%h3{:style => "margin-top: 0; font-size: 2.3rem;"} Search Candidate's name
				= form_tag search_posts_path, method: :get, class: "navbar-form", role: "search" do
					%p
						= text_field_tag :search, params[:search], class: "form-control"
						= submit_tag "Search", name: nil, class: "btn btn-default"
#posts
	- @posts.each do |post|
		.post
			.post_image
				=link_to (image_tag post.image.url(:small)), post
			.post_content
				/ .title
				/ 	%h2= link_to post.position, post
				.data.clearfix
					%p.username
						Posted by 
						= post.user.name
					%p.buttons
						%span
							%i.fa.fa-comments-o
							= post.comments.count
						%span
							%i.fa.fa-thumbs-o-up
							= post.get_likes.size
						%span
							%i.fa.fa-thumbs-o-down
							= post.get_dislikes.size

app/views/posts/show.html.haml
#post_show
	%h4= @post.position
	%p.username
		Posted in about 
		= time_ago_in_words(@post.created_at)
		ago
	.clearfix
		.post_image_description
			= image_tag @post.image.url(:medium)
			%h4 BREIF HISTORY
			.description= simple_format(@post.breifHistory)
			%h4 EDUCATION
			.description= simple_format(@post.education)
			%h4 POLITICAL ACHIEVEMENTS
			.description= simple_format(@post.achievments)
			%h4 FUTURE GOALS
			.description= simple_format(@post.goals)
		.post_data
			=link_to  "Go home", root_path, class: 'button'
			=link_to like_post_path(@post), method: :get, class: "data" do 
				%i.fa.fa-thumbs-o-up
				=pluralize(@post.get_upvotes.size, "Upvotes")
			=link_to dislike_post_path(@post), method: :get, class: "data" do 
				%i.fa.fa-thumbs-o-down
				=pluralize(@post.get_downvotes.size, "downvotes")
			%p.data
				%i.fa.fa-comments-o
				=pluralize(@post.comments.count, "Comment")
			- if @post.user == current_user
				=link_to "Edit", edit_post_path(@post), class: "data"
				=link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?"}, class: "data"
			%br	
			%hr
			%br 
			= social_share_button_tag(@post.position, 'data-twitter-title' => 'TheTitleForTwitter') 



#comments
	%h2.comment_count= pluralize(@post.comments.count, "Comment")
	- @comments.each do |comment|
		.comment
			%p.username= comment.user.name
			%p.content= comment.content
	= render "comments/form"